#!/usr/bin/env python3
"""check_private_repo_scrub.py -- the mechanical check for
practices/private-repo-scrub.md.

# practice: private-repo-scrub

Scope: tree, over practices/*.md specifically -- that directory is
exactly the content this repo ships: per practices/install.md's own Rule,
a consuming repo vendors the whole practices/ tree verbatim. The rule
draws a hard line between content that ships (must stay general) and
content that stays local (the repo's own commit messages, README, and any
future decision record, which can and should keep naming things
precisely) -- so only practices/*.md is in scope here, not the whole
tree.

The private repos this rule exists to protect are named explicitly, not
inferred, because "detect anything that looks like a private repo name"
has no reliable general signature -- this check knows what it's guarding
because it's told, the same way a real blocklist is a list of specific
terms, not a heuristic.

Exit 0 and print nothing when clean. Exit 1 and print the practice's own
Rule text (never a paraphrase) plus the specific finding(s) on a violation.
"""
import pathlib
import json
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
PRACTICE_FILE = ROOT / "practices" / "private-repo-scrub.md"
PRACTICES_DIR = ROOT / "practices"

# The private repos this rule protects. Update this list if either is
# renamed, or if a new private set is added under the same account.
PRIVATE_TERMS = [
    "precedent-individual",
    "precedent-team-maintainers",
    "themorgan/precedent-individual",
    "themorgan/precedent-team-maintainers",
    "github.com/themorgan/precedent-individual",
    "github.com/themorgan/precedent-team-maintainers",
]


# --- shared:scope-helper — keep byte-identical across every copy ---
# --- scope: this repo's own content only ---------------------------------
#
# A check runs in two very different places. In the SOURCE repo that
# authors these practices, everything is authored and everything is in
# scope. In a CONSUMING repo, `practices/` is precedent_materialize.py's
# output and the universal source's `path` (e.g. `process/upstream/`) is a
# vendored copy of somebody else's tree -- content this repo did not write
# and cannot fix. Reporting a finding there is noise: the fix belongs in
# the source, and the consumer's only options are to ignore its own gate or
# to hand-edit a file the next sync overwrites.
#
# 2026-09-06, in a real four-source consumer: no-stale-counts reported 81
# findings, 81 of them inside materialized practices/ and vendored
# process/upstream/; private-repo-scrub reported 12 of 26 there. A gate
# that loud is a gate nobody reads.
#
# Attributed by the COMMITTED MANIFEST.json (which precedent_materialize.py
# writes, recording exactly which files it produced) and by precedent.json's
# declared source paths -- never by which sources happen to resolve in this
# environment, which is the mistake that once failed a repo's own CI on
# every team- and individual-sourced file because a bare checkout can reach
# neither. A repo-local source at `local/` stays in scope: that IS the
# repo's own hand-authored content.
def _foreign_prefixes() -> tuple:
    out = set()
    cfg = ROOT / "precedent.json"
    if cfg.is_file():
        try:
            for s in json.loads(cfg.read_text(encoding="utf-8")).get("sources", []):
                p = str(s.get("path", "")).strip().strip("/")
                if p and p != "local" and not p.startswith("..") and (ROOT / p).is_dir():
                    out.add(p + "/")
        except (OSError, json.JSONDecodeError, AttributeError):
            pass
    return tuple(sorted(out))


def _materialized_files() -> frozenset:
    mf = ROOT / "MANIFEST.json"
    if not mf.is_file():
        return frozenset()
    try:
        m = json.loads(mf.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return frozenset()
    files = {f"practices/{e['slug']}.md" for e in m.get("practices", []) if "slug" in e}
    files |= {e["path"] for e in m.get("checks", []) if "path" in e}
    return frozenset(files)


_FOREIGN = _foreign_prefixes()
_MATERIALIZED = _materialized_files()


# A file whose own header says it is generated is not this repo's text
# either, whoever produced it. `generated-artifact-provenance` requires the
# marker precisely so nothing hand-edits the output; a check that then
# demands a hand-edit there is asking for the one thing the file forbids,
# and the fix has to go to the generator anyway. 2026-09-06: a mirrored
# voice pack, whose first line reads "GENERATED FILE - do not hand-edit",
# was the last thing standing between a real consumer and a clean run.
_GENERATED_MARKERS = ("do not hand-edit", "do not edit", "generated file",
                      "derived artifact", "auto-generated", "autogenerated")


def _looks_generated(rel) -> bool:
    p = ROOT / rel
    try:
        with p.open(encoding="utf-8", errors="ignore") as fh:
            head = "".join(next(fh, "") for _ in range(6)).lower()
    except OSError:
        return False
    return any(m in head for m in _GENERATED_MARKERS)


def not_ours(rel) -> bool:
    """True when `rel` is content this repo vendored, materialized, or
    generated rather than wrote."""
    rel = str(rel).replace("\\", "/")
    return (rel.startswith(_FOREIGN) or rel in _MATERIALIZED
            or _looks_generated(rel))
# --- end shared:scope-helper ---


def rule_text() -> str:
    text = PRACTICE_FILE.read_text(encoding="utf-8")
    m = re.search(r"## Rule\n(.*?)\n## ", text, re.S)
    return m.group(1).strip() if m else "(no Rule found)"


def find_violations() -> list[str]:
    findings = []
    for path in sorted(PRACTICES_DIR.glob("*.md")):
        if not_ours(path.relative_to(ROOT)):
            continue
        text = path.read_text(encoding="utf-8")
        for lineno, line in enumerate(text.splitlines(), start=1):
            for term in PRIVATE_TERMS:
                if term in line:
                    findings.append(
                        f"{path.relative_to(ROOT)}:{lineno}: names a private repo "
                        f"({term!r}) in vendored content: {line.strip()!r}"
                    )
    return findings


if __name__ == "__main__":
    findings = find_violations()
    if findings:
        print(f"VIOLATION: {PRACTICE_FILE.stem}")
        for f in findings:
            print(f"  {f}")
        print("\nthe rule:")
        print("  " + rule_text().replace("\n", "\n  "))
        sys.exit(1)
    sys.exit(0)
